export enum BusinessCategory {
	MICRO = "micro",
	SMALL = "small",
	MEDIUM = "medium",
}

export enum LGCCategory {
	URBAN = "urban",
	SEMI = "semi-urban",
	RURAL = "rural",
}

export enum LGCRevenueHeadCategory {
	SHOP_RATE = "SHOP RATE ",
	TENEMENT_RATE = "TENEMENT RATES/GROUND RENT PRIVATE AND COMMERCIAL PROPERTY ",
	SLAUGHTER_RATE = "SLAUGHTER SLAB FEE ",
	MERRIMENT_RATE = "MERRIMENT AND ROAD CLOSURE LEVIES ",
	FOOD_RATE = "FOOD LICENSES PERMIT (FOR RESTAURANTS, BAKERIES AND OTHER PLACE WHERE FOOD IS SOLD  ",
	MARRIAGE_RATE = "MARRIAGE, BIRTH AND DEATH REGISTRATION FEES ",
	CUSTOMARY_RITE = "CUSTOMARY RIGHT OF OCCUPANCY ",
	MARKET = "MARKET RATES &LEVIES ",
	MOTOR_PARK = "MOTOR PARK LEVIES ",
	BICYCLE_RATE = "Bicycle, Truck, Canoe, Wheelbarrow and Cart Fees ",
	DOMESTIC_ANIMAL = "DOMESTIC ANIMAL LICENSE FEES ",
	CATTLE_LEVY = " CATTLE LEVY ",
	RELIGIOUS_PERMIT = "RELIGIOUS PLACES ESTABLISHMENT PERMIT FEES ",
	SIGN_BORAD = "SIGN BOARD (SIGNAGE) AND ADVERT PERMIT FEES  ",
	CONVENIENCE = "PUBLIC CONVENIENCE, SEWAGE AND REFUSE DISPOSAL FEES AND BATHING HOUSE LICENSE ",
}
